name: scan-ksu
on: workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: https://github.com/mpaujiah-ctrl/SukiSU-Ultra
          ref: "builtin"
          path: sukisu
          fetch-depth: 1
      
      - name: Scan
        run: |          
          cd crdroid
          grep -rn "ksu_selinux_hide_handle" .
          sed -n 365,385p sulog/event.c
          grep -rn "user_arg_ptr" sulog/ *.h | head -20
          grep -n "sulog\|selinux" Makefile Kconfig
                   
      
